# MAIN
APP_NAME = 'Projekt - aplikacja finansowa'
WIDTH = 900
HEIGHT = 600
MENU_HEIGHT = 50
ENTRY_LEFT_WIDTH = 300

IMAGE_SIZE = (24, 24)
MEDIUM_IMAGE_SIZE = (34, 34)
LARGE_IMAGE_SIZE = (48, 48)
# FONTS
# --LOGIN SCREEN
LS_TITLE_FONT = ('Roboto Medium', 23)
LS_ENTRY_FONT = ('Arial', 13)
LS_LABEL_FONT = ('Arial', 10)
# --APP
TITLE_FONT = ('Roboto Medium', 26)
MEDIUM_TITLE_FONT = ('Roboto Medium', 20)
SMALL_TITLE_FONT = ('Roboto Medium', 16)
FONT = ('Roboto Medium', 14)
SMALL_FONT = ('Roboto Medium', 12)
VERY_SMALL_FONT = ('Roboto Medium', 10)

# COLORS
COLOR_CLICKED_MENU_BUTTON = ('#D1D5D8', '#2A2D2E')
COLOR_UNCLICKED_MENU_BUTTON = ("gray75", "gray30")
COLOR_APP_BACKGROUND = ('#D1D5D8', '#2A2D2E')
COLOR_APP_FOREGROUND = ('#D7D8D9', '#343638')
